spring:
  application:
    name: multi-env-jdbc
  profiles:
    active: dev
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: info,health

app:
  datasource:
    host: localhost
    port: 5432
    name: mydb
    username: user
    password: pass
    useCloudDb: false

