spring:
  application:
    name: multi-env-jdbc
  main:
    allow-bean-definition-overriding: true


spring.profiles.active: dev

app:
  datasource:
    host: localhost
    port: 5432
    name: mydb
    username: user
    password: pass

    useCloudDb: false
