spring.application.name=lab4

# --- Conexiunea la PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5433/lab4
spring.datasource.username=postgres
spring.datasource.password=1234

# --- Set?ri JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Server ---
server.port=8080

# --- RabbitMQ Configuration ---
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# --- RabbitMQ DLQ & Retry Configuration ---
spring.rabbitmq.listener.simple.default-requeue-rejected=false
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=2000
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.multiplier=1.5
spring.rabbitmq.listener.simple.retry.max-interval=10000

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN

